"""create linked_commits table

Revision ID: 53b24a19da86
Revises: 1ee607eeacd2
Create Date: 2026-08-31 13:09:03.871323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b24a19da86'
down_revision: Union[str, Sequence[str], None] = '1ee607eeacd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linked_commits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repo', sa.Text(), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo', 'commit_sha', 'ticket_id', name='uq_linked_commits_repo_sha_ticket')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('linked_commits')
    # ### end Alembic commands ###
